      - name: Cari Semua File Android.mk
        run: |
          echo "Mencari semua file Android.mk di seluruh folder:"
          find . -name "Android.mk"
          
          echo "---"
          echo "Isi dari Android.mk yang ditemukan:"
          find . -name "Android.mk" -exec cat {} +
          
