name: Build CSPB Debug

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug Lokasi File
        run: |
          echo "Daftar file Android.mk yang ditemukan:"
          find . -name "Android.mk"
          
          echo "Daftar semua folder:"
          ls -R
          
